name: Suite de Pruebas Automatizadas QA

on:
  push:
    branches: [ "master", "main" ]

jobs:
  ejecutar-pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4 # <-- Actualizado a v4

      - name: 2. Instalar Java 17 en la nube
        uses: actions/setup-java@v4 # <-- Actualizado a v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 3. Ejecutar pruebas de TestNG con Maven
        run: mvn clean test

      - name: 4. Guardar Reporte HTML (Evidencia)
        if: always()
        uses: actions/upload-artifact@v4 # <-- ¡AQUÍ ESTABA EL ERROR! Actualizado a v4
        with:
          name: Reporte-ExtentReports
          path: Reporte_QA.htmll